exports.users =  [
        {
            _id: "5e270a0e2647322352129dae",
            firstName: "Dor",
            lastName: "Ben Lulu",
            age: 25,
            status: "Single",
            desiredRelationship: "Serious Relationship",
            interestedIn: ["Women", "Men"],
            gender: "Male",
            picture: "https://storage.googleapis.com/binder_users_images/DorBenLulu.jpg",
        },
        {
            _id: "5e270a0e2647322352129daf",
            firstName: "Efrat",
            lastName: "Harel",
            age: 26,
            status: "Single",
            desiredRelationship: "Serious Relationship",
            interestedIn: ["Men","Women"],
            gender: "Female",
            picture: "https://storage.googleapis.com/binder_users_images/Efrat.jpg",
        },
        {
            _id: "5e28fe74d80c499f21afeffd",
            firstName: "Vicki",
            lastName: "Menashe",
            age: 28,
            status: "Single",
            desiredRelationship: "Serious Relationship",
            interestedIn: ["Men", "Women"],
            gender: "Female",
            picture: "https://storage.googleapis.com/binder_users_images/Vicki.jpeg",
        },
        {
            _id: "5e270a0e2647322352129db1",
            firstName: "Haim",
            lastName: "Ruso",
            age: 29,
            status: "Single",
            desiredRelationship: "Serious Relationship",
            interestedIn: ["Men", "Women"],
            gender: "Male",
            picture: "https://storage.googleapis.com/binder_users_images/Haim.jpg",
        },
        {
            _id: "5e28fed2d80c499f21aff678",
            firstName: "Yoni",
            lastName: "Shalev",
            age: 36,
            status: "Single",
            desiredRelationship: "Hookups",
            interestedIn: ["Men", "Women"],
            gender: "Male",
            picture: "https://storage.googleapis.com/binder_users_images/Yoni.jpg",
        },
        {
            _id: "5e270a0e2647322352129db0",
            firstName: "Eyal",
            lastName: "Pundak",
            age: 32,
            status: "Single",
            desiredRelationship: "Serious Relationship",
            interestedIn: ["Men", "Women"],
            gender: "Male",
            picture: "https://storage.googleapis.com/binder_users_images/Eyal.jpg", 
        }
    ]

exports.userIds = [
    "5e270a0e2647322352129dae",
    "5e270a0e2647322352129daf",
    "5e270a0e2647322352129db0",
    "5e270a0e2647322352129db1",
    "5e28fe74d80c499f21afeffd",
    "5e28fed2d80c499f21aff678"
]